version: '3'
services:
  main:
    image: kali:latest
    env_file:
      - .flaskenv
    build: .
    ports:
      - "8000:5000"
    environment: 
      - PYTHONPATH=/fitness_app/venv:/fitness_app/venv/bin
      - PATH=/home/fitness_app/bin
    volumes:
      - ./app:/home/fitness_app/app
    #networks:
    #  - scrap

# Uncomment with API added      
  #chromeselenium:
  #  image: joyzoursky/python-chromedriver:3.7-selenium
  #  tty: true #example
  #  volumes:
  #    - app:/home/fitness_app/app
  #selenium-hub:
  #  image: selenium/hub:3.141
  #  container_name: selenium-hub
  #  ports:
  #    - 4444:4444
  #  networks:
  #    - scrap

  #chrome:
  #  shm_size: 2g
  #  volumes:
  #    - /dev/shm:/dev/shm
  #  image: selenium/node-chrome:3.141
#    image: selenium/standalone-chrome:3.141.59-copernicium
  #  depends_on:
  #    - selenium-hub
  #  environment:
  #    - HUB_HOST=selenium-hub
  #    - HUB_PORT=4444
  #  networks:
  #   - scrap

#networks:
#  scrap: