"""users table

Revision ID: 909f448ac99a
Revises: c4b83d0702bb
Create Date: 2019-02-12 19:31:21.580846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909f448ac99a'
down_revision = 'c4b83d0702bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
