"""trainings table

Revision ID: a2f0ab729274
Revises: aca68b42da96
Create Date: 2019-01-31 15:30:21.746967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f0ab729274'
down_revision = 'aca68b42da96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('your_trainig', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_timestamp'), 'train', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_timestamp'), table_name='train')
    op.drop_table('train')
    # ### end Alembic commands ###
