"""users table

Revision ID: e07d4a3ba212
Revises: c35af9664ce3
Create Date: 2019-01-22 15:55:06.479265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07d4a3ba212'
down_revision = 'c35af9664ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cell_number', sa.BIGINT(), nullable=True))
    op.add_column('user', sa.Column('club_site_login', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('club_site_password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'club_site_password')
    op.drop_column('user', 'club_site_login')
    op.drop_column('user', 'cell_number')
    # ### end Alembic commands ###
